<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="language" content="en">
	<meta name="robots" content="index, follow">

	<meta name="author" content="fab1aly">
	<meta name="description" content="Old lovely films from internetarchive.org.">
	<meta name="keywords" content="film, cinema, movie, video, streaming, free, download, watch, online, netflix, hulu, disney, amazon, youtube, vimeo, dailymotion, vudu, google, apple, microsoft, amazon, netflix, hulu, disney, amazon, youtube, vimeo, dailymotion, vudu, google, apple, microsoft, ">

	<!--Favicon-->
	<link rel="icon" href=".\image\logo.png">
	<!-- PWA -->
	<!-- <link rel="manifest" href="manifest.webmanifest" /> -->

	<!--CSS-->
	<!-- <link rel="stylesheet" href="css/style.css" type="text/css"> -->
	<!--Script Fontawesome-->
	<!-- <script src="https://kit.fontawesome.com/fdc6c3e4a2.js" crossorigin="anonymous"></script> -->

	<!-- PicoCSS -->
	<link
		rel="stylesheet"
		href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
	<link
		rel="stylesheet"
		href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css">
	<link
		rel="stylesheet"
		href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.indigo.min.css">

	<!-- HTMX -->
	<script src="https://unpkg.com/htmx.org@2.0.4"></script>

	<!-- AlpineJS -->
	<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>


	<title><?= $title ?></title>
</head>

<body class="pico-background-indigo-800">
	<header class="container-fluid">
		<?php include 'header.phtml'; ?>
	</header>

	<main class="container">
		<?= $viewContent ?>
	</main>

	<footer class="container-fluid">
		<?php include 'footer.phtml'; ?>
	</footer>

	<?php include 'script.phtml'; ?>
</body>

</html>