<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /home/fabien/Code/retroVision/app/views/user/user-dialog.latte */
final class Template_0c3d466124 extends Latte\Runtime\Template
{
	public const Source = '/home/fabien/Code/retroVision/app/views/user/user-dialog.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<dialog id="user_dialog"
    x-ref="dialog"
    x-on:click.outside="">
    
    <article>
        <header>
            <button x-on:click="$refs.dialog.close()" aria-label="Close" rel="prev"></button>
            <p>
                <strong>';
		if (isset($user)) /* line 10 */ {
			echo 'Account';
		} else /* line 10 */ {
			echo 'Welcome';
		}
		echo '</strong>
            </p>
        </header>

        <main id="user_dialog_main">
        </main>
    </article>
</dialog>
';
	}
}
