<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /home/fabien/Code/retroVision/app/views/user/user-element.latte */
final class Template_19c06ba508 extends Latte\Runtime\Template
{
	public const Source = '/home/fabien/Code/retroVision/app/views/user/user-element.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<details id="user-detail" 
    class="dropdown"
    hx-swap-oob="true"
    x-data="{ openDropdown: false }"
    x-ref="dropdown"
    x-on:click.outside="openDropdown = false">

    <summary>
        ';
		if (isset($user)) /* line 10 */ {
			echo 'Account';
		} else /* line 10 */ {
			echo 'Welcome';
		}
		echo '
    </summary>
    
    <ul id="user_links">
';
		if (isset($user)) /* line 14 */ {
			echo '            <li id="user_profile_link">
                <a href="/user/profile"
                    hx-boost="true"
                    hx-push-url="false"
                    hx-trigger="click"
                    hx-target="#user_dialog_main"
                    hx-swap="innerHTML"
                    hx-vals=\'{"user_request": "user_profile"}\'
                    x-on:click="$refs.dialog.showModal()"
                >Profile</a>
            </li>
            <li><a href="#">Favorite</a></li>
            <li><a href="/user/logout">Logout</a></li>
';
		} else /* line 29 */ {
			echo '            <li id="sign_in_link">
                <a href="/user/sign-in"
                    hx-boost="true"
                    hx-push-url="false"
                    hx-target="#user_dialog_main"
                    hx-swap="innerHTML"
                    hx-vals=\'{"user_request": "sign_in"}\'
                    x-on:click="$refs.dialog.showModal()"
                >Sign In</a>
            </li>
            <li id="sign_up_link">
                <a href="/user/sign-up"
                    hx-boost="true"
                    hx-push-url="false"
                    hx-target="#user_dialog_main"
                    hx-swap="innerHTML"
                    hx-vals=\'{"user_request": "sign_up"}\'
                    x-on:click="$refs.dialog.showModal()"
                >Sign Up</a>
            </li>
';
		}
		echo '    </ul>
</details>
';
	}
}
