<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /home/fabien/Code/retroVision/app/config/../views/user/user-form.latte */
final class Template_119f61024a extends Latte\Runtime\Template
{
	public const Source = '/home/fabien/Code/retroVision/app/config/../views/user/user-form.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<form id="user_form" 
    hx-post="/user/';
		echo LR\Filters::escapeHtmlAttr(($this->filters->replace)($user_request, '_', '-')) /* line 2 */;
		echo '"
    hx-trigger="submit" 
    hx-target="#user_dialog_main" 
    hx-swap="innerHTML" 
    x-ref="form"
>

    <fieldset>
        <legend class="container-fluid">
            ';
		if ($user_request === 'sign_up') /* line 11 */ {
			echo 'Sign Up';
		}
		echo '
            ';
		if ($user_request === 'sign_in') /* line 12 */ {
			echo 'Sign In';
		}
		echo '
            ';
		if ($user_request === 'sign_forget') /* line 13 */ {
			echo 'Forget Password';
		}
		echo '
            ';
		if ($user_request === 'user_profile') /* line 14 */ {
			echo ' Update Profile';
		}
		echo '
        </legend>

';
		if ($user_request === 'sign_up' || $user_request === 'user_profile') /* line 17 */ {
			echo '        <label for="username_form">
            Username
        </label>
        <input id="username_form" 
            title="Please enter your username" 
            type="text" 
            name="';
			echo LR\Filters::escapeHtmlAttr($user_request !== 'user_profile' ? 'username' : 'new_username') /* line 24 */;
			echo '"
            placeholder="';
			echo LR\Filters::escapeHtmlAttr($user_request === 'user_profile' ? htmlspecialchars($_SESSION['user']->getUsername()) : '') /* line 25 */;
			echo '" 
            value="';
			echo LR\Filters::escapeHtmlAttr($_SESSION['formSignData']['username'] ?? '') /* line 26 */;
			echo '" 
            ';
			if ($user_request !== 'user_profile') /* line 27 */ {
				echo 'required';
			}
			echo '
        >
';
		}
		echo '
        <label for="email_form">
            Email
        </label>
        <input id="email_form" 
            title="Please enter your email" 
            type="email" 
            name="';
		echo LR\Filters::escapeHtmlAttr($user_request !== 'user_profile' ? 'email' : 'new_email') /* line 37 */;
		echo '" 
            placeholder="';
		echo LR\Filters::escapeHtmlAttr($user_request === 'user_profile' ? htmlspecialchars($_SESSION['user']->getEmail()) : 'you@home.me') /* line 38 */;
		echo '" 
            value="';
		echo LR\Filters::escapeHtmlAttr($_SESSION['formSignData']['email'] ?? '') /* line 39 */;
		echo '" 
            ';
		if ($user_request !== 'user_profile') /* line 40 */ {
			echo 'required';
		}
		echo '
        >

';
		if ($user_request !== 'sign_forget') /* line 43 */ {
			echo '        <label for="password_form">
            ';
			echo LR\Filters::escapeHtmlText($user_request === 'user_profile' ? 'New Password' : 'Password') /* line 45 */;
			echo '
        </label>
        <input id="password_form" 
            title="Please enter your password" 
            type="password" 
            name="';
			echo LR\Filters::escapeHtmlAttr($user_request === 'user_profile' ? 'new_password' : 'password') /* line 50 */;
			echo '" 
            placeholder="********" 
            pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9])(.{8,})$"
            value="';
			echo LR\Filters::escapeHtmlAttr($_SESSION['formSignData']['password'] ?? '') /* line 53 */;
			echo '" 
            ';
			if ($user_request !== 'user_profile') /* line 54 */ {
				echo 'required';
			}
			echo '
        >
';
		}
		echo "\n";
		if ($user_request === 'sign_up' || $user_request === 'user_profile') /* line 58 */ {
			echo '        <label for="password_confirm_form">
            Confirm
        </label>
        <input id="password_confirm_form" 
            title="Please confirm your password" 
            type="password" 
            name="';
			echo LR\Filters::escapeHtmlAttr($user_request !== 'user_profile' ? 'password_confirm' : 'new_password_confirm') /* line 65 */;
			echo '" 
            placeholder="" 
            ';
			if ($user_request !== 'user_profile') /* line 67 */ {
				echo 'required';
			}
			echo '
        >
';
		}
		echo '    </fieldset>

    <button type="submit" hx-on:submit="this.setAttribute(\'aria-busy\',\'true\');">
        ';
		echo LR\Filters::escapeHtmlText($user_request === 'user_profile' ? 'Update' : 'Submit') /* line 73 */;
		echo '
    </button>

    <hr>

';
		if ($user_request === 'user_profile') /* line 78 */ {
			echo '    <button 
        type="button" 
        class="pico-background-red-600 pico-color-white" 
        hx-trigger="click" 
        hx-delete="/user/profile" 
        hx-target="#user_dialog_main" 
        hx-swap="innerHTML" 
        hx-vals="js:{password: prompt(\'Please enter your password to confirm\')}" 
        hx-on:click="" 
        hx-confirm="Are you sure you want to delete your account?" 
        hx-on:htmx:after-request="this.setAttribute(\'aria-busy\',\'true\');">
        <i class="fa-solid fa-arrows-rotate"></i><span>Delete Account</span>
    </button>
';
		} else /* line 92 */ {
			echo '    <a 
        href="/user/';
			if ($user_request === 'sign_up') /* line 94 */ {
				echo 'sign-in';
			}
			if ($user_request === 'sign_in') /* line 94 */ {
				echo 'forget';
			}
			if ($user_request === 'sign_forget') /* line 94 */ {
				echo 'sign-up';
			}
			echo '" 
        hx-boost="true" 
        hx-push-url="false" 
        hx-target="#user_dialog_main" 
        hx-swap="innerHTML">
        <span>
            ';
			if ($user_request === 'sign_up') /* line 100 */ {
				echo 'Or sign-in here';
			}
			echo '
            ';
			if ($user_request === 'sign_in') /* line 101 */ {
				echo 'Forgot password';
			}
			echo '
            ';
			if ($user_request === 'sign_forget') /* line 102 */ {
				echo 'Or sign-up here';
			}
			echo '
        </span>
    </a>
';
		}
		echo '
</form>';
	}
}
