<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /home/fabien/Code/retroVision/app/views/layout/header.latte */
final class Template_a5fd904bc1 extends Latte\Runtime\Template
{
	public const Source = '/home/fabien/Code/retroVision/app/views/layout/header.latte';


	public function main(array $ʟ_args): void
	{
		echo '<header class="container-fluid">
<nav>
	<ul id="nav_logo">
		<li>
			<a href="/">
				<h1>retroVision</h1>
			</a>
		</li>
	</ul>
	<ul id="nav_search">
		<li>
			<form role="search">
				<input name="search" type="search" placeholder="THX 1138" aria-label="Search" />
				<input type="submit" value="Search" />
			</form>
		</li>
	</ul>
	<ul id="nav_menu">
		<li id="nav_menu_buttons" role="group">
			<button hx-get="/home"
				hx-trigger="click"
				hx-target="main"
				hx-swap="innerHTML"
				hx-push-url="true">News</button>
			<button>Top</button>
			<button>Trend</button>
		</li>
		<li id="nav_menu_user" x-data="{}">
		</li>
	</ul>
</nav>
<hr />
</header>';
	}
}
