<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /home/fabien/Code/retroVision/app/config/../views/home.latte */
final class Template_6f890bbcd4 extends Latte\Runtime\Template
{
	public const Source = '/home/fabien/Code/retroVision/app/config/../views/home.latte';


	public function main(array $ʟ_args): void
	{
		echo '

<main class="container">
<hgroup class="overflow-auto">
    <h2 class="pico-color-pumpkin-300">Truc bidule</h2>
    <hr>
    <section class="grid">
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
    </section>
</hgroup>
<hgroup>
    <h2 class="pico-color-pumpkin-200">Truc bidule</h2>
    <hr>
    <section class="grid">
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
        <article>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, minus aperiam ratione eveniet consequatur veniam, placeat voluptas excepturi facere minima magni.</p>
        </article>
    </section>
</hgroup>
</main>
';
	}
}
